DROP TABLE IF EXISTS t_user_mng;
CREATE TABLE t_user_mng (
    USER_SN BIGINT AUTO_INCREMENT PRIMARY KEY,
    EMAIL VARCHAR(50) NOT NULL UNIQUE,
    PASSWORD VARCHAR(255) NOT NULL,
    NAME VARCHAR(10) NOT NULL,
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS t_keyword_mng;
CREATE TABLE t_keyword_mng (
    KEYWORD_SN BIGINT AUTO_INCREMENT PRIMARY KEY,
    KEYWORD VARCHAR(50) NOT NULL UNIQUE,
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS t_site_mng;
CREATE TABLE t_site_mng (
   SITE_SN BIGINT AUTO_INCREMENT PRIMARY KEY,
   SITE_NM VARCHAR(100) NOT NULL,
   SITE_PATH VARCHAR(255) NOT NULL,
   CLASS_NM VARCHAR(100) NOT NULL,
   REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS t_news_mng;
CREATE TABLE t_news_mng (
    NEWS_SN BIGINT AUTO_INCREMENT PRIMARY KEY,
    TITLE VARCHAR(255) NOT NULL,
    HREF TEXT NOT NULL,
    REG_DATE TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);